CREATE SCHEMA `backup_inventario_chips` ;

CREATE TABLE `backup_inventario_chips`.`chips` (
`id` int not null auto_increment,
  `id_chip` INT NOT NULL,
  `operadora` ENUM(	'Audax',
					'Ceará', 
                    'Cia Net', 
                    'City', 
                    'Correios Celular', 
                    'Cruzeiro Celular', 
                    'Dry Conect', 
                    'Elo', 
                    'Esquadrão Celular', 
                    'Flu mobile', 
                    'Fortaleza Celular', 
                    'FutCelular', 
                    'Gospel', 
                    'GR6 Celular', 
                    'Maga+', 
                    'Paraisópolis Celular', 
                    'Repom', 
                    'Santos FC', 
                    'SPFC', 
                    'Sport', 
                    'TelBe', 
                    'Vascão', 
                    'Vasco', 
                    'VestCasa', 
                    'Wantel') NOT NULL,
  `DDD` ENUM('11', 
			 '12', 
             '13', 
             '14', 
             '15', 
             '16', 
             '17', 
             '18', 
             '19', 
             '21', 
             '22', 
             '23', 
             '24', 
             '25', 
             '26', 
             '27', 
             '28', 
             '29', 
             '31', 
             '32', 
             '33', 
             '34', 
             '35', 
             '36', 
             '37', 
             '38', 
             '39', 
             '41', 
             '42', 
             '43', 
             '44', 
             '45', 
             '46', 
             '47', 
             '48', 
             '49', 
             '51', 
             '52', 
             '53', 
             '54', 
             '55', 
             '56', 
             '57', 
             '58', 
             '59', 
             '61', 
             '62', 
             '63', 
             '64', 
             '65', 
             '66', 
             '67', 
             '68', 
             '69', 
             '71', 
             '72', 
             '73', 
             '74', 
             '75', 
             '76', 
             '77', 
             '78', 
             '79', 
             '81', 
             '82', 
             '83', 
             '84', 
             '85', 
             '86', 
             '87', 
             '88', 
             '89', 
             '91', 
             '92', 
             '93', 
             '94', 
             '95', 
             '96', 
             '97', 
             '98', 
             '99') NOT NULL,
  `MSISDN` INT(11) NOT NULL,
  `ICCID` INT(19) NOT NULL,
  `Status` ENUM('Inativo', 
				'Ativo', 
                'Grace 1', 
                'Grace 2', 
                'Grace 3', 
                'Expirado') NOT NULL,
  `Data de Expiração` DATE NOT NULL,
  `Titular do Chip` VARCHAR(15) NOT NULL DEFAULT 'Surf Telecom',
  PRIMARY KEY (`id`));